# Generated by Django 5.1.1 on 2024-10-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('ref_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('fit_id', models.CharField(max_length=20)),
            ],
        ),
    ]
