# Generated by Django 4.2.16 on 2024-10-12 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_no', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='application',
            name='apl_no',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('traveller_no', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('mem_status', models.BooleanField()),
                ('mem_name', models.CharField(max_length=20)),
                ('mem_birth', models.DateTimeField()),
                ('apl_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.application')),
                ('mem_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.member')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('apl_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.application')),
            ],
        ),
    ]
