# Generated by Django 4.2.16 on 2024-10-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_member_remove_application_id_remove_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
        ),
    ]
