# Generated by Django 4.2.16 on 2024-10-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
