# Generated by Django 5.1.1 on 2024-10-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reservation'),
        ('users', '0006_application_user'),
    ]

    operations = [
    ]
